import type { Metadata } from 'next'
import '../styles/globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from '@/components/ui/sonner'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/themes/theme-provider'

const inter = Inter({
  subsets: ['latin'],
  preload: true,
})

export const metadata: Metadata = {
  title: 'Nesto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            // disableTransitionOnChange
          >
            <main className="flex-grow">{children}</main>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
