import type { Metadata } from 'next'
import '../styles/globals.css'
// import Footer from '@/components/Footer'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from '@/components/ui/sonner'
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  preload: true,
})

export const metadata: Metadata = {
  title: 'Nesto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="fixed inset-0 -z-10 pointer-events-none">
          <div className="h-full w-full bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:14px_24px] [mask-image:radial-gradient(ellipse_80%_50%_at_50%_0%,#000_70%,transparent_110%)] opacity-50 animate-grid-pan-slow dark:opacity-70" />
        </div>
        <Toaster />
        <ClerkProvider>
          <main className="flex-grow">{children}</main>
          {/* <Footer /> */}
        </ClerkProvider>
      </body>
    </html>
  )
}
