import type { Metadata } from 'next'
import '../styles/globals.css'
import Container from '@/components/ui/Container'
import Header from '@/components/ui/Header'
import Footer from '@/components/ui/Footer'
import { ClerkProvider } from '@clerk/nextjs'
import { neobrutalism } from '@clerk/themes'

import { Inter } from 'next/font/google'

const inter = Inter({})

export const metadata: Metadata = {
  title: 'Nesto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ClerkProvider
          appearance={{
            baseTheme: neobrutalism,
          }}
        >
          <Container>
            <main className="flex-grow">
              <Header />
              {children}
            </main>
            <Footer />
          </Container>
        </ClerkProvider>
      </body>
    </html>
  )
}
